name: Build and Release luci-app-auto-login IPK

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git subversion libncurses5-dev zlib1g-dev gawk flex quilt xsltproc wget unzip python3 python3-pip

    - name: Clone OpenWrt 23.05.5
      run: |
        git clone -b v23.05.5 https://github.com/openwrt/openwrt.git openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Copy plugin to OpenWrt package directory
      run: cp -r . ./openwrt/package/luci-app-auto-login

    - name: Configure target
      run: |
        cd openwrt
        echo "CONFIG_TARGET_amlogic=y" > .config
        echo "CONFIG_TARGET_amlogic_meson8b=y" >> .config
        echo "CONFIG_PACKAGE_luci-app-auto-login=y" >> .config
        make defconfig

    - name: Compile plugin
      run: |
        cd openwrt
        make package/luci-app-auto-login/compile V=s

    - name: Upload IPK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-auto-login-ipk
        path: openwrt/bin/packages/*/luci/luci-app-auto-login*.ipk

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: "luci-app-auto-login v${{ github.run_number }}"
        body: "Automatically built luci-app-auto-login.ipk from commit ${{ github.sha }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload IPK to Release
      uses: softprops/action-gh-release@v1
      with:
        files: openwrt/bin/packages/*/luci/luci-app-auto-login*.ipk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
