name: Build luci-app-auto-login IPK

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git subversion libncurses5-dev zlib1g-dev gawk flex quilt xsltproc wget unzip python3 python3-pip python3-setuptools python3-wheel

    - name: Clone OpenWrt 23.05.5
      run: |
        git clone -b v23.05.5 https://github.com/openwrt/openwrt.git openwrt
        cd openwrt
        # 清理旧 feeds 并更新
        ./scripts/feeds clean
        for i in {1..3}; do ./scripts/feeds update -a && break || sleep 5; done
        ./scripts/feeds install -a

    - name: Copy plugin
      run: |
        mkdir -p openwrt/package/luci-app-auto-login
        cp -r * openwrt/package/luci-app-auto-login/ || true
        # 忽略无法复制自身目录的错误

    - name: Configure target
      run: |
        cd openwrt
        # 使用标准 x86_64 目标测试，避免 amlogic 报错
        echo "CONFIG_TARGET_x86_64=y" > .config
        echo "CONFIG_PACKAGE_luci-app-auto-login=y" >> .config
        make defconfig

    - name: Compile plugin
      run: |
        cd openwrt
        make package/luci-app-auto-login/compile V=s

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-auto-login-ipk
        path: openwrt/bin/packages/*/luci/luci-app-auto-login*.ipk
