name: Build OpenWrt Luci Plugin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses5-dev gawk git subversion unzip python3 python3-pip

    - name: Download OpenWrt
      run: |
        mkdir openwrt
        cd openwrt
        git init
        git remote add origin https://github.com/openwrt/openwrt.git
        git fetch --depth 1 origin master
        git checkout FETCH_HEAD
        cd ..

    - name: Copy plugin to OpenWrt package
      run: |
        mkdir -p openwrt/package/luci-app-auto-login
        cp -r luci root Makefile README.md openwrt/package/luci-app-auto-login/

    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Build toolchain
      run: |
        cd openwrt
        make tools/install -j$(nproc)
        make package/libs/toolchain/compile -j$(nproc)

    - name: Compile plugin
      run: |
        cd openwrt
        make package/luci-app-auto-login/compile V=s -j$(nproc)

    - name: Upload built plugin
      uses: actions/upload-artifact@v3
      with:
        name: luci-app-auto-login-ipk
        path: openwrt/bin/packages/*/*/luci-app-auto-login*.ipk
