name: Build luci-app-auto-login IPK

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git subversion libncurses5-dev zlib1g-dev gawk flex quilt xsltproc wget unzip python3 python3-distutils python3-setuptools

    - name: Clone OpenWrt 23.05.5
      run: |
        git clone -b v23.05.5 https://github.com/openwrt/openwrt.git openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Copy plugin
      run: |
        cp -r ./luci-app-auto-login ./openwrt/package/

    - name: Configure target
      run: |
        cd openwrt
        cat > .config <<EOF
CONFIG_TARGET_amlogic=y
CONFIG_TARGET_amlogic_meson8b=y
CONFIG_PACKAGE_luci-app-auto-login=y
EOF
        make defconfig

    - name: Compile luci-app-auto-login only
      run: |
        cd openwrt
        make package/luci-app-auto-login/compile V=s

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-auto-login-ipk
        path: openwrt/bin/packages/*/luci/luci-app-auto-login*.ipk
